- package.py
Also removed examples/fixtures/dirtree folder with demo files, there is a script for it.
I'd suggest to make a minor version change for this.
> fix: overlooked env dumping on DEBUG3

- package.py
8f0c5e6 *package.py - allow heredoc commands, don't apply patterns for explicitly specified single file*
94ec6bb *package.py - Fixed patterns applying without specified commands*
> fix: Fixed patterns applying

- package.py
- package.tf
* Added patch from #29, will close #29 after additional testing on Windows.
**Git log:**
9ddf8c7 *package.py - Detect OS and use correct executable for pip requirements*
c5beb69 *package.tf - Detect OS and use appropriate executable name*
cf507ea *package.py - Fixed issue with zip renaming on Win platform*
> fix: Fixed issue with zip renaming on Windows platform

- examples/simple/main.tf
- iam.tf
When Lambda@Edge is used it replaces the region in the resource ARN of the IAM policy with a wildcard (*).
Lambda@Edge is then able to put its logs in every region where it is executed.
Resolves #34.
> fix: Adds region wildcard to log group arn when lambda@edge

- README.md
- examples/complete/main.tf
- examples/with-efs/README.md
- examples/with-efs/main.tf
- examples/with-efs/outputs.tf
- main.tf
- variables.tf
- versions.tf
Resolves #44
To support the new `file_system_config` which allows Lambdas to have EFS file systems mounted.
No breaking changes.
- Tested on a project that requires file_system_config. 
- Tested Plan & Apply. Works as expected.
```
Terraform v0.12.29
+ provider.aws v2.70.0
+ provider.external v1.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
```
```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
```
> feat: Add support for EFS File System Config

- iam.tf
Replace exclusive policy attachments with regular attachments for managed policies (i.e. policies specified via either `policy` or `policies` parameters).
Tested on terraform 0.12.29.
Resolves #40.
> fix: Fix policy attachments for managed policies

- package.py
Added workaround for OSX XCode python interpreter, but still doesn't know how to reproduce on OSX a situation when OSX XCode python interpreter becomes a main interpreter observable by terraform.
Also added an exception that better explains the issue with missing python interpreter version.
> Fix: os xcode python interpreter

- package.py
A bit of fixes relative to paths processing in case of concurrent builds and in case of symlinks in a content root directories.
**Git log:**
95b41be *fix: paths creation in case of concurrent builds, closes #64*
80d0926 *Don't silently ignore content by symlinks*
e1320a7 *fix: take build_plan into account when computing hash*
> fix: Fixed concurrent builds

- package.tf
> fix: Removed hash_extra_paths to have the same hash for multiple executors

- .gitignore
- .pre-commit-config.yaml
- README.md
- examples/alias/versions.tf
- examples/async/versions.tf
- examples/build-package/versions.tf
- examples/container-image/README.md
- examples/container-image/context/Dockerfile
- examples/container-image/context/empty
- examples/container-image/main.tf
- examples/container-image/outputs.tf
- examples/container-image/versions.tf
- examples/deploy/versions.tf
- examples/multiple-regions/versions.tf
- examples/simple/versions.tf
- examples/with-efs/README.md
- examples/with-efs/versions.tf
- examples/with-vpc/versions.tf
- main.tf
- modules/alias/versions.tf
- modules/deploy/versions.tf
- variables.tf
- versions.tf
Resolves #79
- AWS has recently [announced support for container images](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/) 
- [v3.19.0+](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.19.0) of the AWS Provider for terraform already [supports it](https://github.com/hashicorp/terraform-provider-aws/pull/16512). 
No breaking changes.
- Tested on a project that uses container image.
- Tested the example added in this PR 
- Tested Plan & Apply. Works as expected.
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.19.0
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider …
```
> feat: Add support for creating lambdas that use Container Images

- README.md
- variables.tf
Minor change to README to indicate the IAM role ARN should be used when using lambda_role
Since the only requirement is a string, you could pass the IAM role name, or other string type properties.
The error on apply (ValidationException) isn't inherently descript enough to know exactly what was wrong.
none
Reviewed Markdown
> docs: Explicitly state the IAM role property used for lambda_role

- README.md
- package.py
Changed the wording and included the failing `source_path` when it can't be found.  Added explanation to both the error message and the README.md regarding how relative paths are interpreted.
I spent 30 minutes trying to interpret "source_path must be set" when it was set, but its relativity was wrong.
None.
Manual testing with valid and invalid paths.  This is my first time using the module, so I don't have a complex source_path, so complex source_paths aren't tested.
> docs: Improved package.py error message for missing source_paths

- README.md
- examples/alias/README.md
- examples/async/README.md
- examples/build-package/README.md
- examples/container-image/README.md
- examples/deploy/README.md
- examples/multiple-regions/README.md
- examples/simple/README.md
- examples/with-efs/README.md
- examples/with-vpc/README.md
- iam.tf
- main.tf
- modules/alias/README.md
- modules/alias/main.tf
- modules/deploy/README.md
- modules/deploy/main.tf
- modules/deploy/variables.tf
> docs: update description of hook vars, note naming expectations of default policy

- modules/deploy/main.tf
It appears AWS CodeDeploy will reject deployments where the CurrentVersion and TargetVersion match (edit: if the deployment config is anything other than all-at-once, e.g. canary or linear rollout). We avoid creating such a failing deployment by ignoring cases where the current and target versions already match in the deploy script.
Fixes #82, where there's a lot more detail on the motivation here.
> fix: skip creating deployments if current and target versions match

- README.md
- examples/event-source-mapping/README.md
- examples/event-source-mapping/main.tf
- examples/event-source-mapping/outputs.tf
- examples/event-source-mapping/versions.tf
- iam.tf
- main.tf
- outputs.tf
- variables.tf
#102 
Add missing event source mapping config
none
Added example module and verified triggers
> feat: event source mapping

- .gitignore
- .pre-commit-config.yaml
- README.md
- examples/alias/README.md
- examples/async/README.md
- examples/build-package/README.md
- examples/complete/README.md
- examples/container-image/README.md
- examples/deploy/README.md
- examples/multiple-regions/README.md
- examples/simple/README.md
- examples/with-efs/README.md
- examples/with-vpc/README.md
- modules/alias/README.md
- modules/deploy/README.md
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A
> chore: update documentation based on latest `terraform-docs` which includes module and resource sections

- README.md
- iam.tf
- outputs.tf
New output for the log group name.
Resolves #110 
I need the log group name for a metric filter resource.
None.
Can see the output value.
> feat: Add output for lambda CloudWatch log group name

- .github/workflows/pre-commit.yml
- README.md
- examples/alias/README.md
- examples/alias/versions.tf
- examples/async/README.md
- examples/async/versions.tf
- examples/build-package/README.md
- examples/build-package/versions.tf
- examples/complete/README.md
- examples/complete/versions.tf
- examples/container-image/README.md
- examples/container-image/versions.tf
- examples/deploy/README.md
- examples/deploy/versions.tf
- examples/event-source-mapping/versions.tf
- examples/multiple-regions/README.md
- examples/multiple-regions/versions.tf
- examples/simple/README.md
- examples/simple/versions.tf
- examples/with-efs/README.md
- examples/with-efs/versions.tf
- examples/with-vpc/README.md
- examples/with-vpc/versions.tf
- modules/alias/README.md
- modules/alias/versions.tf
- modules/deploy/README.md
- modules/deploy/versions.tf
- versions.tf
- only run validate check on min terraform version
- we will use max version supported to run all pre-commit checks, but only perform validation on min supported version
- no
- static checks
> chore: only run validate check on min terraform version

- README.md
- examples/alias/README.md
- examples/async/README.md
- examples/build-package/README.md
- examples/complete/README.md
- examples/container-image/README.md
- examples/deploy/README.md
- examples/multiple-regions/README.md
- examples/simple/README.md
- examples/with-efs/README.md
- examples/with-vpc/README.md
- modules/alias/README.md
- modules/deploy/README.md
- fix documentation due to terraform docs 0.11.2 update
- current ci-cd checks are failing for users to do this update/change
- no
- static ci-cd checks
> chore: fix documentation due to terraform docs 0.11.2 update

- .github/workflows/pre-commit.yml
- README.md
- examples/alias/README.md
- examples/alias/versions.tf
- examples/async/README.md
- examples/async/versions.tf
- examples/build-package/README.md
- examples/build-package/versions.tf
- examples/complete/README.md
- examples/complete/versions.tf
- examples/deploy/README.md
- examples/deploy/versions.tf
- examples/event-source-mapping/versions.tf
- examples/multiple-regions/README.md
- examples/multiple-regions/versions.tf
- examples/simple/README.md
- examples/simple/versions.tf
- modules/alias/README.md
- modules/alias/versions.tf
- modules/deploy/README.md
- modules/deploy/versions.tf
- versions.tf
- revert module Terraform 0.13.x version upgrade
- update ci-cd checks to validate each Terraform root directory 
- min version used will vary greatly, this update allows examples to have various minimum versions of Terraform and still be tested separate from what the module min version is itself
- No
- CI/CD checks
> fix: revert module Terraform 0.13.x version upgrade 

- iam.tf
- modules/deploy/README.md
- modules/deploy/main.tf
- modules/deploy/variables.tf
- outputs.tf
Include `interpreter` argument of `provisioner.local_exec` block as variable in `null_resource.deploy`.  Allow user to control the execution runtime of the deploy script.
`/bin/bash` isn't necessarily guaranteed to be the selected shell, leading to failures in bash built-in control flow.  
See issue <>
> feat: Added interpreter variable to control script runtime

- README.md
- main.tf
- variables.tf
adding variable acl and server_site_encryption for s3_bucket_object resource
my bucket where I keep lambda code is encrypted and has different acl
nope
on internal dev env
> feat: Add s3_acl and s3_server_site_encryption variables

- iam.tf
Defaults the role_name to `*` within the coalesce to workaround #83.  By setting a dummy value as the default option, terraform can successfully import without erroring out because the variables are empty and null.  If one still forgot to set both values, an error will be thrown when attempting to create any of the IAM resources with the `*` value.
```
Error: invalid value for name (must match [\w+=,.@-])
on .terraform/modules/application.lambda/iam.tf line 71, in resource "aws_iam_policy" "logs":
71:   name   = "${local.role_name}-logs"
```
We still use terraform 0.12 and would like to upgrade to at least v1.29.0 at least up to v1.39.0.  See #83 for details involving the current issue.
No breaking changes.  If anyone is using v1.39.0, it is locked to terraform 0.13 anyways and it seems …
> fix: Defaults the role_name coalesce to * to workaround import error

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- README.md
- examples/alias/README.md
- examples/async/README.md
- examples/build-package/README.md
- examples/complete/README.md
- examples/container-image/README.md
- examples/deploy/README.md
- examples/multiple-regions/README.md
- examples/simple/README.md
- examples/triggers/README.md
- examples/with-efs/README.md
- examples/with-vpc/README.md
- modules/alias/README.md
- modules/deploy/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
> chore: update documentation and pin `terraform_docs` version to avoid future changes

- .github/workflows/pre-commit.yml
- iam.tf
The async policy is missing the action to asynchronously call other lambda functions. Duplicate of #140, which I messed up somehow due to using github UI for the first time.
Added lambda:InvokeFunction into the policy document for async integrations.
Check https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html as it states
"This operation requires permission for the lambda:InvokeFunction action."
When I deployed a lambda of which the destination_on_success is another lambda arn, my caller lambda failed to call my callee lambda due to a permission error.
Does not break backwards compatibility as it is an added permission.
After adding the above changes on my local terraform module, the lambda integration works as expected, i.e. it has the permission to call another lambda …
> fix: permission for lambda-to-lambda async calls

- package.py
- package.tf
Removed the `working_dir` option from `package.tf`.
Fixes an issue where using the `-chdir` option breaks because it can't find the `package.py` file.
https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/135
No
Tested by running both `terraform -chdir=tf apply` and `cd tf && terraform apply`, both passed without throwing an error.
> fix: package.py not found with -chdir option

- README.md
- examples/complete/README.md
- examples/complete/main.tf
- iam.tf
- variables.tf
This change allows a better customization for the `trusted entities` used in the assume role policy
For example :
```hcl
trusted_entities = [
{
type = "AWS",
identifiers = ["arn:aws:sts::XXXXXXXXXXXX:assumed-role/OktaRoleForXXX/xxxx@xxxx"]
}
]
```
Currently, `trusted_entities` input variable only accepts a list of strings which is added to the type `Service` of the assume role Principal.
For example:
```hcl
trusted_entities = ["service.amazonaws.com"]
```
Will be interpreted as :
```
Principal = {
~ Service = "lambda.amazonaws.com" -> [
+ "lambda.amazonaws.com",
+ "service.amazonaws.com",
]
}
```
In the issue https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/138 I explain that we need a `AWS` Principal in our assume role (the goal is to execute lambda in local using its …
> feat: Extended `trusted_entities` variable to support multiple types

- .pre-commit-config.yaml
- examples/complete/README.md
- examples/complete/main.tf
- examples/complete/versions.tf
> feat: Added example to show creation of Lambdas with for_each

- README.md
- examples/simple/main.tf
From reviewing #62 I discovered the solution for the error mentioned in that issue has been found but not yet documented for future users. This change is intended to begin documenting the special `:zip` command so future module users do not end up confused why they are getting a Python error from what appears to be a properly configured module usage.
This fixes the documentation issue discovered in #62.
This is a documentation change only, no breaking changes.
Documentation change, no testing.
> fix: add documentation for the :zip command. fixes #62

- examples/complete/main.tf
- main.tf
Make the AWS Lambda function explicitly depend on the Cloudwatch log group. With this change, Terraform will create the log group before the lambda, and delete it after deleting the lambda.
This avoids a race condition where AWS creates the log group before Terraform can (see below). 
If the lambda function writes logs when the log group doesn't exist, then AWS will create it, and Terraform will error with "log group already exists" on the following `terraform apply`.
It's possible to trigger this case by running `terraform destroy` when the lambda function is being invoked: the log group will be
deleted by Terraform and recreated by AWS before the lambda function is destroyed.
This change imposes an ordering between the lambda function and the log group creation/destruction, avoiding …
> fix: make lambda function depend on the Cloudwatch log group

- examples/event-source-mapping/main.tf
- iam.tf
- main.tf
Uncommenting `destination_config` block within event_source_mapping. Git pre-commit hook performed a `terraform fmt` resulting in additional formatting changes to unrelated code.
I'm really not familiar with this module, but I tested it locally by specifying an `event_source_mapping` config similar to what is in `examples/event-source-mapping`. A `plan` and `apply` worked just fine and i could see that the "On-Failure" destination config was now configured under a dynamoDB trigger for my lambda function. I re-ran a `plan` again afterwards just to validate that no other spurious side-effects/changes were detected.
> feat: Added destination_config in aws_lambda_event_source_mapping

- README.md
Fixes https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/155
> chore: Remove checked checkboxes to make module docs render properly

- .pre-commit-config.yaml
- README.md
- iam.tf
- modules/alias/README.md
- modules/alias/versions.tf
- modules/deploy/README.md
- modules/deploy/main.tf
- modules/deploy/variables.tf
- modules/deploy/versions.tf
- versions.tf
- add tags to `aws_iam_policy` resources
- currently the resources are not tagged
- no
> chore: add tags to `aws_iam_policy` resources

- README.md
- variables.tf
Adding precisions regarding the S3 bucket handling.
I faced validation issues because i was using the `arn` instead of the `id` of the bucket. As i saw similar people having this issue on internet, i thought it would be better to clarify this in the documentation.
None
> docs: Updated README with S3 bucket id handling

- README.md
- versions.tf
Remove unnecessary provider requirement
Introduces unneeded provider requirement on downstream users of this module.
Fix #167
Should not break anything, as random provider was unreferenced in main module.
Did a successful `terraform plan` in examples/simple, and encountered no problems.
Code inspection of other examples showed that they all declare random as a required provider if they use it.
> fix: Remove `random` provider because it is not used

- modules/docker-build/README.md
- modules/docker-build/main.tf
- modules/docker-build/variables.tf
Simple PR to expose ECR variables related to image tag mutability & scan on push. Defaults are backward compatible.
Give the user the ability to choose lambda image build immutability & vulnerability scanning
N/A
```
cd examples/container-image && \
terraform init && \
terraform apply -target module.docker_image -auto-approve && \
terraform destroy -target module.docker_image -auto-approve
```
> feat: Expose ecr tag & scan variables in docker-build module

- main.tf
Add topics parameter for lambda event source
Add support to set topics for lambda event source. This is optional parameter for MSK according to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping
No
Tested in my project. `topics` parameter can be attached for MSK event source mapping.
> feat: Add topics parameter support for lambda event source

- CHANGELOG.md
- README.md
- examples/complete/README.md
- examples/complete/main.tf
- main.tf
- variables.tf
Ignores changes to the source code hash of the lambda function code to maintain an idempotent terraform build in cases where the application code (lambda package) deployment is managed by an external pipeline / party.
Because the content of `lifecycle` `ignore_changes` lists cannot be dynamically generated, this update simply sets the `aws_lambda_function`'s optional  argument `source_code_hash` to `null` if the new variable `ignore_source_code_hash` is set to `true`.
Allow terraform to manage infrastructure components and application developers to manage the application code
none
> feat: Add support for separate deployments of infra and code

- main.tf
There is no need to set the [optional `etag` field of the `aws_s3_bucket_object` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object#etag) as the filename is a hash of the content that only changes when the actual content changes.
Setting `etag` to a computed MD5 hash of the locally built zip archive used to always trigger changes.
When building packages on several workspaces, the MD5 sum of the locally built zip archive always changes.
Setting the `TF_RECREATE_MISSING_LAMBDA_PACKAGE` to `false` alone does not resolve that issue.
N/A
When package source content changes, the hash of the zip archive changes, it is properly uploaded to S3, and the Lambda is properly updated to use that version.
> fix: No need to set `aws_s3_bucket_object` `etag` as filename is already a hash of the content

- README.md
- examples/alias/README.md
- examples/alias/versions.tf
- examples/async/README.md
- examples/async/versions.tf
- examples/build-package/README.md
- examples/build-package/versions.tf
- examples/deploy/README.md
- examples/deploy/versions.tf
- examples/event-source-mapping/README.md
- examples/event-source-mapping/main.tf
- examples/event-source-mapping/versions.tf
- examples/multiple-regions/README.md
- examples/multiple-regions/versions.tf
- examples/simple/README.md
- examples/simple/versions.tf
- examples/triggers/README.md
- examples/triggers/versions.tf
- main.tf
- modules/alias/README.md
- modules/alias/versions.tf
- modules/deploy/README.md
- modules/deploy/versions.tf
- versions.tf
Allow to configure `queues` and `source_access_configuration` properties in [lambda_event_source_mapping](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping) configuration.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-mq.html
Add missing parameters that are required to configure AmazonMQ event source type.
None.
Tested locally by modifying the `examples/event-source-mapping` module to include Amazon MQ event source.
> feat: Add Amazon MQ event source type support

- package.py
Allows the **docker_pip_cache** property to work on macOS. 
Without this, the **docker_pip_cache** property is hard-coded to be ignored unless the host platform is Linux.
No breaking compatibility.
Works great on my Mac, using Docker for Mac, and it's got the M1 chip. I don't see or know why macOS was excluded, unless it was just an oversight in ensuring it didn't happen on Windows.
I could see it not working if the intent was to share a pip cache with the host, but that's not what it's doing. It's just creating a separate directory mapped into the container that gets reused between builds. And that's great! But macOS users would benefit from it, too.
> feat: Added docker pip cache support for macOS

- package.py
Sort directories and files to ensure they are always processed in the same order during hashing and zip file creation.
The order files are walked is not determined by default which can result in different archives created from different workspaces:
```
.terraform/lambda-start-scheduled-execution-builds/81c20fecbe4e25f6e7dce7b8ee1a151ea6c76e84eeb25cc937f8ddbeeff54777.zip) <(unzip -vl .terraform/lambda-start-scheduled-exe
cution-builds/f6c01d9d2d57cd416967d66704cc421eb24f72aab55da0fd18f7e676ab8a5491.zip)
Archive:  .terraform/lambda-start-scheduled-execution-builds/81c20fecbe4e25f6 | Archive:  .terraform/lambda-start-scheduled-execution-builds/f6c01d9d2d57cd41
Length   Method    Size  Cmpr    Date    Time   CRC-32   Name                   Length   Method    Size  Cmpr    Date    Time …
```
> fix: Sort directories and files to ensure they are always processed in the same order

- .github/workflows/pre-commit.yml
- README.md
- outputs.tf
Added unique_id output of the created lambda role.
We have s3 bucket policies that use the unique role id to restrict access to specific roles. This make sure I can create the lambda role with the module instead of creating the role separately or using a data resource to get the required variable.
Doesn't break anything as far as I am aware.
Applied this using terraform 13.4 and 1.0 and used the output of this feature
> feat: Add unique_id output of the lambda role

- package.py
This PR takes patterns into account when computing hash.
This should resolve #53.
Without this change, files that are excluded from Zip packages with `!` prefixed patterns are still considered during hash computing, which triggers diff when plans are run on workspaces from different users.
Example plan of the `examples/build-package` configuration from `master` branch:
```
[1600662] prepare: QUERY: {
"artifacts_dir": "builds",
"hash_extra": "",
"hash_extra_paths": "[]",
"paths": "{\"cwd\":\"/home/patrick/workspaces/terraform/terraform-aws-modules/terraform-aws-lambda/examples/build-package\",\"module\":\"../..\",\"root\":\".\"}",
"runtime": "python3.8",
"source_path": "[{\"pip_requirements\":\"./../fixtures/python3.8-app1/requirements.txt\"},\"./../fixtures/python3.8-app1/index.py\",{\"pat …
```
> fix: Take patterns into account when computing hash

- README.md
- examples/complete/main.tf
- main.tf
- variables.tf
This change strips the leading `./` in S3 key if `artifacts_dir` is set to something like `${path.root}/mypath/`.
Without this change, this configuration:
```
module "lambda-my-layer" {
source  = "terraform-aws-modules/lambda/aws"
version = "2.4.0"
create_layer = true
layer_name   = "my-layer"
runtime         = "python3.8"
build_in_docker = true
source_path = [{
path             = "${path.module}/lambda/my-layer/",
pip_requirements = true,
prefix_in_zip    = "python",
}]
artifacts_dir = "${path.root}/.terraform/lambda-builds/"
store_on_s3             = true
s3_bucket               = aws_s3_bucket.mybuckt.bucket
s3_object_storage_class = "STANDARD"
}
```
gives the following plan excerpt:
```
+ resource "aws_lambda_layer_version" "this" {
+ arn                         = (known after apply) …
```
> fix: Strip leading `./` in S3 key

- README.md
- package.py
- package.tf
- variables.tf
Add `recreate_missing_package` parameter in addition to `TF_RECREATE_MISSING_LAMBDA_PACKAGE` environment variable.
People can forget defining the `TF_RECREATE_MISSING_LAMBDA_PACKAGE` environment variable to `false` before running `terraform plan` or `terraform apply`, leading to undesired diff.
Adding this as a parameter, we can make sure it is always defined when desired.
N/A
When the `TF_RECREATE_MISSING_LAMBDA_PACKAGE` environment variable is set to `true` or `false`, it takes precedence over the new `recreate_missing_package` parameter which defaults to `true`.
> feat: Add `recreate_missing_package` parameter

- README.md
> docs: Added a mention of good examples - 1Mill/serverless-tf-examples

- README.md
- examples/complete/main.tf
- iam.tf
- variables.tf
Add support for additional `assume_role_policy` statements on the `aws_iam_role` via a new variable, `assume_role_policy_statements`.
Fixes #196
None
Added `assume_role_policy_statements` to the `complete` example. The observed `assume_role_policy` statements on the  `aws_iam_role` is as expected. As this is a new variable, it should have no impact on the existing code.
> feat: add support for additional assume_role_policy statements

- README.md
- examples/async/README.md
- examples/async/main.tf
- examples/async/versions.tf
- examples/complete/main.tf
- main.tf
- variables.tf
- versions.tf
Allow to configure `architectures` property in [aws_lambda_function](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function) and `compatible_architectures` property in [aws_lambda_layer_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version) configuration.
Add missing parameter that is required to support AWS Lambda Functions Powered by AWS Graviton2 Processor.
https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/
None.
Closes #207
> feat: Add support for AWS Graviton2 powered functions

- modules/deploy/main.tf
closes terraform-aws-modules/terraform-aws-lambda/issues/224
When CodeDeploy fails to finish the deployment, Terraform doesn't realize it and keeps processing. This PR makes the Terraform apply fail whenever the code deploy fails.
> fix: Raise failure when CodeDeploy deployment fails

- modules/docker-build/README.md
- modules/docker-build/main.tf
- modules/docker-build/variables.tf
Support for Cross-Account ECR for docker-build module
AWS Lambda now supports cross-account container image pulling from Amazon Elastic Container Registry https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-support-cross-account-image-amazon-elastic-container-registry/
None
- I have tested and validated these changes using this example
```terraform
module "docker_image" {
source = "../../modules/docker-build"
create_ecr_repo = false
ecr_address     = "XXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com"
ecr_repo        = random_pet.this.id
image_tag       = "1.0"
source_path     = "context"
build_args = {
FOO = "bar"
}
}
```
> feat: Added support for Cross-Account ECR for docker-build module

- modules/deploy/README.md
- modules/deploy/main.tf
- modules/deploy/variables.tf
Automatically creates the IAM permissions for CodeDeploy to invoke the before traffic hook and after traffic hook.
It can be turned off with a new variable, `attach_hooks_policy`.
fixes #226
> feat: Added required IAM permissions for CodeDeploy hooks

- examples/deploy/main.tf
- modules/deploy/README.md
- modules/deploy/main.tf
- modules/deploy/variables.tf
Adding here 2 minor tweaks to the deploy sub-module that I found useful.
1) When I deploy multiple lambdas and use the `wait_deployment_completion` the AWS is throttling the CLI calls and the script fails. Here, I'm introducing the `get_deployment_sleep_timer` variable that it can increase the sleep time. Also the sleep time is a random number between `(0  and 10) + ${get_deployment_sleep_timer}`.
2) I want to separate the infrastructure deployment from the lambda lambda function release via CodeDeploy. The motivation behind this is to capture any issues that introduced by the infrastructure changes.
An example is, you change the permissions for a resource that a lambda function use, the old version immediately louses access and you wait until the traffic switches to the new version that …
> feat: Added support for random sleep delay in deploy submodule

- modules/deploy/main.tf
Fix the following error when `wait_deployment_completion = true` 
```
│ Status: InProgress...
│ /bin/bash: command substitution: line 29: syntax error near unexpected token `+'
│ /bin/bash: command substitution: line 29: `( $RANDOM % 5 ) + 20'
```
Tested it in my private repo
```
module.demo.null_resource.deploy[0] (local-exec): Status: Created...
module.demo.null_resource.deploy[0] (local-exec): Sleeping for: 22 Seconds
module.demo.null_resource.deploy[0]: Still creating... [10s elapsed]
module.demo.null_resource.deploy[0]: Still creating... [20s elapsed]
module.demo.null_resource.deploy[0] (local-exec): Status: InProgress...
module.demo.null_resource.deploy[0] (local-exec): Sleeping for: 22 Seconds
module.demo.null_resource.deploy[0]: Still creating... [30s elapsed] …
```
> fix the sleep_time variable

- examples/container-image/main.tf
- modules/docker-build/README.md
- modules/docker-build/main.tf
- modules/docker-build/variables.tf
Let users add ECR lifecycle policy rules to automate the cleaning up of unused images generated by the `docker-build` module.
I use this module to build and publish many Docker Images to ECR and I want to be able to easily delete unneeded Docker Images. Since this module is the one building and publishing the Docker Images to ECR it seems best to extend the module to also support the JSON ECR lifecycle policy document. 
This is not a breaking change and is only added non-breaking functionality to the module. 
```hcl
// examples/container-image/main.tf
module "docker_image" {
source = "../../modules/docker-build"
create_ecr_repo = true
ecr_repo        = random_pet.this.id
image_tag       = "1.0"
source_path     = "context"
build_args = {
FOO = "bar"
}
ecr_repo_lifecycle_policy = <<EOF
{ …
```
> feat: Add ECR Lifecycle Policy Option to docker-build module

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/stale-actions.yaml
- .pre-commit-config.yaml
- .releaserc.json
- examples/async/outputs.tf
- examples/event-source-mapping/README.md
- examples/event-source-mapping/versions.tf
- examples/fixtures/python3.8-app1/ignore_please.txt
- Update `.releaserc.json` to ensure conventional-commit standards are used by semantic-releaser
- Update `.pre-commit-config.yaml` versions to latest and ensure `end-of-file-fixer` hook is used
- Add `pr-title.yml` GitHub workflow for ensuring PR titles follow conventional-commit standards
- Fix `release.yml` GitHub workflow to ensure release process does not run on forks; ref https://github.com/terraform-aws-modules/meta/issues/25
- Add `stale-actions.yaml` to ensure issues and pull requests are routinely cleaned up; copie from EKS repository
- Ensure organization configurations are aligned and standardized; most of these changes are copied from the current EKS repository
- No
- CI checks only
> chore: Update release configuration files to correctly use conventional-commits

- package.py
Allow the use of third party images to build dependencies other that `lambci` images.
The current implementation requires docker images that have a worker pointing to `/var/task`, since it forces the mount point to that location. It prevents the user to user an official image or any other image that does has the working directory in `/var/task`.
If you try to create a lambda for example, using `build_in_docker = true` it will fail because the workdir is empty. And if you try to use `pip_requirements` to install the requirements, it will throw an error saying it couldn't find `requirements.txt` - because the workdir is not the same as the mount point.
With this change we set the workdir to `/var/task` in the `docker run` command, so no matter which image you use, the mount point and the …
> feat: Allow the use of third party images to build dependencies

- README.md
- examples/event-source-mapping/main.tf
- examples/event-source-mapping/versions.tf
- main.tf
- versions.tf
I added an optional argument in `aws_lambda_event_source_mapping` definition.
https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/254
No breaking changes that the new line I added in this PR is optional argument.
I used `examples/event-source-mapping/main.tf` for testing.
First I applied it before this change, and then I added a new configuration in the example such as below.
```
event_source_mapping = {
sqs = {
event_source_arn = aws_sqs_queue.this.arn
function_response_types = ["ReportBatchItemFailures"] # added this line
}
dynamodb = {
...
```
After that, I applied again and got as below.
```
Terraform will perform the following actions:
~ resource "aws_lambda_event_source_mapping" "this" {
~ function_response_types            = [
+ "ReportBatchItemFailures",
]
id …
```
> feat: Accept new arguments `function_response_types` in `aws_lambda_event_source_mapping`

- iam.tf
- main.tf
- modules/alias/main.tf
- modules/alias/outputs.tf
- modules/deploy/main.tf
- modules/deploy/outputs.tf
- outputs.tf
Fixed #251 
And updated code style.
> fix: Updated code style to use `try()`

- main.tf
> fix: Fixed event source mapping filter criteria

- modules/docker-build/README.md
- modules/docker-build/main.tf
- modules/docker-build/variables.tf
- modules/docker-build/versions.tf
Supports `keep_remotely` `docker_registry_image` variable.
Fixes #283
Workaround for problems described in #283 
None, defaults to `false` as the provider has it set.
> fix: Added support for keep_remotely in docker-build submodule

- README.md
- examples/build-package/README.md
- examples/build-package/main.tf
- examples/fixtures/nodejs14.x-app1/index.js
- examples/fixtures/nodejs14.x-app1/package.json
- package.py
Fully based on #292 where I didn't have permission to push changes. Fixes #292.
1. Add support to build automatically npm dependencies, with docker support. 
2. Change default docker image from lambci to official AWS SAM images
As made for pip requirements, this PR adds support to build Nodejs dependencies automatically with or without docker.
This PR simplifies the process needed to build and deploy Nodejs functions and, thanks to docker, allows users to build functions without the need to have the interpreter installed locally
No breaking changes introduced
- [ x ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [ x ] I have also tested the real deployment of Python and Nodejs functions with and without dependencies.
> feat: Add support to build automatically npm dependencies

- examples/complete/main.tf
Removed hard-coded AWS account ID from examples/complete and added data resource to lookup current AWS account
Remove hard-coded AWS account ID from examples/complete and added data resource to lookup current AWS account
Unable to build the examples/complete  main.tf because the AWS account id is hard-coded.
No
> fix: Removed hard-coded AWS account id in examples

- examples/complete/README.md
- examples/event-source-mapping/main.tf
- main.tf
Resolve #277  issue.
need to kafka brokers. you can use AWS MSK.
```tf
self_managed_kafka = {
batch_size = 100
starting_position = "TRIM_HORIZON"
topics = [
"example-topic-v1"
]
self_managed_event_source = [
{
endpoints = {
KAFKA_BOOTSTRAP_SERVERS = "kafka1.example.com:9092,kafka2.example.com:9092"
}
}
]
source_access_configuration = [
{
type =  "SASL_SCRAM_512_AUTH",
uri = "SECRET_AUTH_INFO"
},
{
type = "VPC_SUBNET",
uri = "subnet:subnet-example"
},
{
type = "VPC_SUBNET",
uri = "subnet:subnet-example"
},
{
type = "VPC_SECURITY_GROUP",
uri = "security_group:sg-example"
}
]
}
```
> feat: Added support for self managed kafka in event source mapping

- main.tf
Set `ephemeral_storage_size = null` if you are running in govcloud region.
Fixes #304
> fix: Fixed ephemeral_storage in AWS govcloud region

- examples/alias/README.md
- examples/alias/main.tf
- examples/alias/outputs.tf
- modules/alias/README.md
- modules/alias/main.tf
- modules/alias/outputs.tf
- modules/alias/variables.tf
This change adds the ability to configure event source mapping on a Lambda Alias, instead of just the base Lambda. The code to configure the event source mapping was pulled from the main Lambda module and ported to the alias module.
We extensively target a Lambda alias for all our use cases in our environment, currently setting this purely via the module isn't possible.
No
Ran terraform apply to `examples/alias` and then made my changes to the module and ran another apply. No changes were detected. Added new examples and ran another apply. Resources deployed successfully.
> feat: Added support for event source mapping in alias submodule

- main.tf
Enabling event source mapping by default.
https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/317#issue-1266390128
> fix: Fixed enabled attribute in Lambda Event Source Mapping by default

- main.tf
Added all policy-attachments to the deponds_on of the 'aws_lambda_function'
When the lambda is created the execution-role with all its
policies should be in place.
Some policies like VPC are a hard requirement for lambda creation
which fill fail if they are not already in place.
Fixes #326 
May introduce circular dependencies, where policies some how depend on the lambda.
Those policies could created / attached outside of this module.
> fix: Lambda should depend on policy attachments

- package.py
Fixes #313 
When a base image contains an entrypoint path, it'll cause an `entrypoint requires the handler name to be the first argument` error to be thrown as the current run commend doesn't override it.
See issue #313. I am not sure when it happened, but the official AWS lambda runtime images started including entrypoints (lambci images still do not).
Nope
Tested and working on my personal project. Official tests still todo:
> fix: Override docker entrypoint when it exists

- outputs.tf
Uses `depends_on` to force the output `local_filename` to wait until the package is available, so the output can be relied on to tailor the terraform graph in cases where the package must be available before it is used.
Fixes #355
See #355
I don't believe there are any breaking changes.
> fix: Forces the local_filename output to wait for the package to be built

- package.py
Fixes #357
Raises plan-time error if the python or nodejs runtime is not present in the PATH. This matches the apply-time behavior, but generates the error during the plan instead of waiting until the apply.
See #357
I don't think so, unless people were somehow exploiting the prior behavior. But I can't really think of a situation where anyone would _want_ a plan-time success and an apply-time failure...
> fix: Generates error in plan phase if runtime is not available

- package.py
`pip_requirements_step` and `npm_requirements_step` are executed even when there is no requirements file, and so there is no package to build. The runtime check should occur _only_ when the package is being built.
See https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/358#issuecomment-1285685758
The opposite! It fixes a breaking change.
> fix: Performs plan-phase runtime check only if building package

- README.md
- package.py
This skips the runtime test when building in docker.
In the plan phase, package.py is executed on the local machine, even when the build is configured to use docker. This means the runtime check was executed on the local machine, and therefore required that the `runtime` be present in the local machine PATH. But when using docker, the runtime should only be required in the container, not on the local machine.
Since by default the image used is based on the runtime, we skip the runtime check when using docker to build the package. However, a note is added to the readme for cases where the user customizes the `docker_image`, as that can lead to a success in the plan phase that would fail in the apply phase, if they are not careful to match up the runtime and the image.
Fixes #361
> fix: Skips the runtime test when building in docker

- main.tf
create_current_version_async_event_config and create_unqualified_alias_async_event_config were not working due to zipmap returning a map with qualifier as key and null as value if variables were set to false
there's currently no way to opt out of either current_version or unqualified_version for async event config
I deployed the `examples/alias` example and modified the variables before my change, resulting in no change in terraform state. Then I applied my change and ran apply, and terraform wanted to remove the resources, as it should.
> fix: Qualifiers in event invoke config

- examples/with-vpc-s3-endpoint/README.md
- examples/with-vpc-s3-endpoint/main.tf
Add dedicated NACL rules for an extra layer of security and dynamically build the ones for the S3 prefix list in the current region, so that **response** traffic from the S3 endpoint is allowed to reach intra subnets where the Lambda function is attached.
Two motivations:
- provide a complete example that also shows how to deal with NACL rules when an S3 Gateway endpoint is involved;
- gather feedback on how NACL rules are dynamically generated for AWS-managed prefix lists using the [nacl-rules-managed-prefix-list module](https://registry.terraform.io/modules/luigidifraiawork/nacl-rules-managed-prefix-list/aws/latest).
Not aware of any.
> chore: Add dedicated NACL rules to intra subnets in example with VPC and S3 Gateway endpoint

- README.md
- examples/build-package/README.md
- examples/build-package/main.tf
- examples/fixtures/python3.8-app1/docker/entrypoint.sh
- package.py
- package.tf
- variables.tf
1. Have added support for additional options to be passed to the docker run command
2. Have added ability to override the entrypoint in the docker run command
This PR replaces #360.  The approach here requires fewer changes to package.py, making it far easier to maintain going forwards.
I want to build my lambdas in docker containers (because my build environment might not have the required pre-requisites installed) but I need access to packages in CodeArtifact. Differences in build environments make this slightly more difficult. On build machines builds are run within containers, so I have Docker in Docker issues. On developers machines, Terraform might be running within a container or it might not. Workarounds to cope with these different environments make for some very ugly code. …
> feat: Support additional arguments for docker and entrypoint override

- CHANGELOG.md
- README.md
- main.tf
- modules/docker-build/README.md
- modules/docker-build/main.tf
- modules/docker-build/versions.tf
This change is to add new resources (sam_metadata_*) of type (null_resource) that will maintain some information about the lambda resources exist in the terraform application to enable the integration with SAM CLI.  SAM CLI tool is looking for the lambda resources source code, and the resources that contain the building logic of these resources. SAM CLI can use this information to extend the SAM CLI testing capabilities to the terraform applications.
This change will enable the customers who use Serverless TF module to define Lambda resources to integrate with SAM CLI tool, and so the customers can test their applications either locally or on cloud.
no breaking changes.
As the new resource is just to collect metadata for SAM CLI tool, so it does not require any changes from the modules …
> feat: Add SAM Metadata resources to enable the integration with SAM CLI tool

- examples/container-image/main.tf
- modules/docker-build/README.md
- modules/docker-build/main.tf
- modules/docker-build/variables.tf
The purpose of this PR is to add support for multi-arch or targeted arch image builds.
Given the prevalence of multi-arch image builds these days, it's likely a good idea to expose platform target via the module.  This allows a user to define, for example: `linux/amd64` or `linux/amd64,linux/arm64`
None
> feat: Expose platform argument to the docker-build module

- modules/docker-build/README.md
- modules/docker-build/versions.tf
The goal of this PR is to resolve docker provider deprecation issues resulting from the docker provider transition to 3.x.  This major update to the provider removes interface compatibility between `docker_image` and `docker_remote_image`.
Resolves: #398 
Ensure the module works out of the box, until the module can be updated to use the latest variant of the `docker` provider implementation.
> feat: Update docker provider pin to 2.x in docker-build submodule

- README.md
- examples/simple/main.tf
- main.tf
- variables.tf
- versions.tf
Implement SnapStart for Java Lambdas.
References:
https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html
https://aws.amazon.com/blogs/compute/starting-up-faster-with-aws-lambda-snapstart/
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#snap_start
Add support for SnapStart enabled lambdas.
_N/A_.
> feat: Add snap_start functionality

- examples/build-package/README.md
- examples/build-package/main.tf
- package.py
This PR fixes building packages with poetry when not building packages with docker.
Resolves #417 
N/A
> fix: Properly construct poetry commands when not using docker for building package

- package.py
Resolves #427 
Root issue is that `docker_additional_options` was added by https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/366 after I started working on adding poetry support in #311, and it was merged before, and I missed it during rebasing.
> fix: Pass docker object to docker_run_command to fix #427

- .pre-commit-config.yaml
- examples/alias/main.tf
- examples/async/main.tf
- examples/build-package/main.tf
- examples/code-signing/main.tf
- examples/complete/main.tf
- examples/container-image/main.tf
- examples/deploy/main.tf
- examples/event-source-mapping/main.tf
- examples/multiple-regions/main.tf
- examples/simple/main.tf
- examples/triggers/main.tf
- examples/with-efs/main.tf
- examples/with-vpc-s3-endpoint/main.tf
- examples/with-vpc/main.tf
- main.tf
Aws recently introduced maximum concurrency of lambda functions when using sqs as an event source ( https://aws.amazon.com/it/blogs/compute/introducing-maximum-concurrency-of-aws-lambda-functions-when-using-amazon-sqs-as-an-event-source/ ), i've added the support of this feature to this module.  
This is my first contribution to this repo, please check the code since i might be wrong.
Limiting lambda concurrency with SQS without setting reserved concurrency.
If you want to set maximum_concurrency_sqs_scaling you need the aws provider >= 4.51.0, because the support for scaling_config has been introduced in 4.51.0: https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4510-january-19-2023
> feat: Support maximum concurrency of Lambda with SQS as an event source

- README.md
- examples/simple/main.tf
- examples/with-efs/README.md
- examples/with-efs/main.tf
- examples/with-vpc/README.md
- examples/with-vpc/main.tf
- iam.tf
- variables.tf
Add ability to specify [maximum session duration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#max_session_duration) for the created role.
We're using this module to create all our services. In development, the developers assume the roles of the services to mimic the permissions they have. By default the sessions can have a maximum duration of an hour (3600 seconds) and that means that developers need to re-assume multiple times per day.
There should be no changes as the default remains the same.
> feat: Add max session duration for IAM role

- README.md
- examples/complete/README.md
- examples/complete/main.tf
- examples/complete/versions.tf
- main.tf
- variables.tf
- versions.tf
Adds suport for the recently-introduced [invoke_mode](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function_url#invoke_mode) argument on the aws_lambda_function_url resource:
https://github.com/hashicorp/terraform-provider-aws/pull/30547
Setting `invoke_mode` to `RESPONSE_STREAM` allows streaming responses via the lambda's Function URL.
More about the brand-new Lambda response streaming:
https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/
None.
> feat: Add invoke_mode input

- README.md
- iam.tf
- variables.tf
Added simple flag, for not create IAM policy which allows to create logs by Lambda@Edge in regions other than N.Virginia.
In some cases that logs are not necessary, but storing it costs extra $.
NO
> feat: Added control to create logs by Lambda@Edge in all regions

- examples/alias/main.tf
- modules/alias/main.tf
PR #402 introduced maximum concurrency to lambda functions.
As I use Aliases, I've added this feature to their module
This is also my first contribution to this repo.
Limiting lambda concurrency with SQS without setting reserved concurrency, while using Lambda Aliases
> feat: Support maximum concurrency of Lambda Alias with SQS as an event source

- README.md
Update `README.md` to clarify that SAM support for Terraform is now released
- https://aws.amazon.com/blogs/compute/aws-sam-support-for-hashicorp-terraform-now-generally-available/
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-terraform-support.html
- Update outdated information
- Encourage usage
N/A
N/A
> docs: SAM Terraform support is now GA

- package.py
Use of npm.cmd on WINDOWS instead of npm within install_npm_requirements method
https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/414 describes the issue, it has been closed with the resolution that WSL should be used. While this is a solution not all development teams use WSL. Additionally, the package.py already contains specific WINDOWS handling anyway (e.g. for python).
Fixes https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/414
no breaking change imho
locally on my Windows machine.
> fix: Fixed npm install on Windows without having to use wsl

- README.md
- examples/complete/main.tf
- main.tf
- variables.tf
- wrappers/main.tf
Adds a `function_tags` input to allow function-only tags to be passed.
We would like to configure tags that are specific to the lambda function and not any other resources created under this module.
No
We have also tested using this feature against our internal infrastructure.
> feat: Allows tags to be provided only to the function

- main.tf
Fixes https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/486
> fix: Set timeouts only when values are given

- .github/workflows/test.yml
- examples/fixtures/python3.8-app2/index.py
- package.py
> chore: Added Ruff (Python code formatter)

- README.md
- package.py
- tests/test_package_toml.py
When running with some source_path setting a command:
```
source_path = [
{
"commands" = XYZ
}
```
It might happen the commands fails and we want to fail the terraform deployment
Before packaging we needed to set some auth token for npm resources. In some rare cases the authentication failed but the build carried on.
No
> feat: Commands should fail the build if their exit code is not zero

- README.md
- examples/complete/main.tf
- main.tf
- variables.tf
- wrappers/main.tf
Inspired by https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/261 to workaround the limitation of 10 tags for S3 objects.
> feat: Added support to override default tags of provider in S3 object

- main.tf
Make the logging configuration only an object on the `aws` partition
See #539 
No
> fix: Dynamic logging config for Gov Cloud

- .github/workflows/lock.yml
- .github/workflows/pr-title.yml
- .github/workflows/pre-commit.yml
- .github/workflows/release.yml
- .github/workflows/stale-actions.yaml
- .pre-commit-config.yaml
- modules/docker-build/README.md
- Update CI workflow versions to remove deprecated runtime warnings
- Updates our workflows to use the latest versions
- Removes the `deprecated runtime` warnings from the workflow execution output
- No
> fix: Update CI workflow versions to remove deprecated runtime warnings

- package.py
Allow `FileNotFoundError` to be ignored on `close()` to compensate for file already being renamed
There appear to be some conditions by which the `self._tmp_filename` file has already been renamed/moved to `self.filename` prior to (or racing with) the calling of `close()`.
In this case `FileNotFoundError` will be thrown, causing the Terraform to fail. But without changing anything, a subsequent run of the Terraform will succeed because the ZIP file already exists. (aka: it was created correctly on the first pass)
> fix: Dont raise FileNotFoundError from close() on tmpfile rename

- package.py
Fixed an attribute error made by typo
This is an error - should be fixed
> fix: AttributeError os.exists is not valid python attribute.

- package.py
- tests/test_package_toml.py
- tests/test_zip_source.py
fixes #557 
adding back the  declaration of `sh_work_dir` that was removed in #534 because the variable is required and consumed [here](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/2202912af9c6e02313e24bd15e3923079addeedc/package.py#L881)
Also, had to refactor to write to a tempfile instead of using the fd 
because in systems where `/bin/sh` -> `/bin/dash`,  it would throw the following error
> fix: Zip source directory should read from sh_work_dir

- main.tf
Update lambda permissions handling so there's no interruption to the permissions available to a lambda.
The change keeps the module interface the same and so there's no changes needed to the documentation.
The only material change visible to users is that the statement_id will now be used as a prefix rather than as a specific value.
When any parameters contain dynamic elements, e.g. `data.aws_region.name`, and that is evaluated in an intermediate module, it is not known until apply time, which causes the permission to he removed and added.  During this window, Cloudwatch Logs will see errors when delivering events to the subscription and stop sending events for 10 minutes.
By switching to a statement_id_prefix and using a create_before_destroy lifecycle we avoid such interruptions.
No …
> feat: Added create before destroy on aws_lambda_permission

- modules/alias/main.tf
… event source mappings, same as lambda function
I have added support in the alias submodule to have multiple event source mapping `filter_criteria` in line with the main lambda function.
I have wasted an entire evening trying to make event source mapping filter_criteria work on the alias with 
`operation error Lambda: CreateEventSourceMapping, https response error StatusCode: 400, RequestID: 4d25b930-c830-49e2-bbc7-dbd4add503f7, InvalidParameterValueException: Invalid filter pattern definition`. 
This is based on the example found [here](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v7.6.0/examples/event-source-mapping/main.tf)
Alias will be in line with the existing documentation.
> feat: Added support for alias to have multiple filter criteria same as function

- package.py
Fixes #592.
Since Python 3.12 changed the default behavior of `tempfile.mkdtemp(suffix=None, prefix=None, dir=None)` (see the documentation [here](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp)) and based on the discussion in the issue, it is recommended to use absolute paths for temporary folders. This pull request addresses that for earlier Python versions.
From now on, the method in the [package.py](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/b88a85627c84a4e9d1ad2a655455d10b386bc63f/package.py#L123) will return an absolute path.
The details are described in issue #592. 
Since this is the proposed solution and all the examples use absolute paths for the temporary folders, it is presumably not a breaking change.
> fix: Always use absolute path to temp folders

- .pre-commit-config.yaml
- README.md
- main.tf
- variables.tf
- wrappers/main.tf
Added the "skip_destroy" argument for the "function" resource. 
More info from the AWS Provider Doc:
(Optional) Set to true if you do not wish the function to be deleted at destroy time, and instead just remove the function from the Terraform state.
Particularly useful for Lambda@Edge that cannot be destroyed if they are still associated with a CloudFront Distribution.
> feat: Added the skip_destroy argument for functions

- main.tf
add `function_url_auth_type` option option to `aws_lambda_permission`
relates to #425 
add cross account permissions
none
Applied and tested on forked version
> feat: Add function_url_auth_type option to aws_lambda_permission

- modules/alias/main.tf
Add support for `self_managed_kafka_event_source_config` and `amazon_managed_kafka_event_source_config` to be able to set custom consumer group ids.
This config is available in lambda function and should be available in alias as well so we can specify custom consumer group ids.
> feat: Add support for kafka event source config

- .github/workflows/pr-title.yml
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- modules/deploy/README.md
- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No
> fix: Update CI workflow versions to latest

- package.py
> fix: Skip broken symlinks on hash computing

- package.py
fe72310 fix: improve sh exec step debug logging
a4fd2e1 feat: allow to don't specify `path` in `source_path` and use explicit `:zip` commands
aa2cb10 fix: make `source_path` blocks independent
> The `source_path` blocks don't impact anymore to each other by workdir changes
38d6715 fix: unify `:zip` path normalization
---
Maybe it makes sense to bump major release version due to changed `source_path` blocks behavior.
> feat: Make `source_path` blocks independent

- package.py
- tests/test_package_toml.py
- tests/test_zip_source.py
With this PR the build plan becomes a list of lists instead of a one flat list.
Every nested list is an independent step from other steps in the plan.
fc9cf82 *fix: radically redesign the build plan form*
0e42fd0 *chore: rename things in package.py*
* Fixes #644
* Closes #645
> feat: Radically redesign the build plan form

- package.py
This change was missed in https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/293. Documentation is up to date, code is not.
Fixes https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/506
Replace https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/507
This would solve inconsistencies in the documentation. It says the field is named `npm_requirements`, but it's in fact `npm_package_json`.
There is no breaking change. The wrongly documented field `npm_requirements` will start to work as expected. The previous non-documented field `npm_package_json` will keep working.
> fix: Rename npm_package_json to npm_requirements

- examples/build-package/main.tf
- package.py
Allows optionally specifying a temp dir for poetry to bring parity with npm and pip
Docker CLI on ubuntu default for github actions, does not allow mounting /tmp https://stackoverflow.com/questions/65267251/docker-bind-mount-directory-in-tmp-not-working
This results in a frustrating situation where terraform passes locally but fails with strange error in CI pipeline.
Fixes: #545 
N/A
Added temp dir to one poetry example and left rest untouched to prove not breaking change
> feat: Allow temp dir for poetry docker builds

- .pre-commit-config.yaml
- modules/deploy/README.md
- modules/deploy/main.tf
- outputs.tf
add data source `aws_partition`
replace hardcoded partition `aws` with `${data.aws_partition.current.partition}` 
This changes is needed so module could correctly work in china and gov regions. 
No breaking changes.
> fix: Add aws_partition to support usage of this module in aws-cn and gov

- package.tf
If dependencies build is performed using Docker, and additional Docker options are specified, and any of those options contain a sensitive value, the content of the archive file has also to be marked as sensitive, to avoid exposing these sensitive options in the Terraform plan. Unfortunately the `external` provider [doesn't support marking output values as sensitive](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/external#result-1), so this workaround seems like an only viable solution.
Fixes https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/676.
None.
> fix: Do not expose output from build command in Docker

- examples/container-image/README.md
- examples/container-image/context/Dockerfile
- examples/container-image/main.tf
- modules/docker-build/README.md
- modules/docker-build/main.tf
- modules/docker-build/variables.tf
- modules/docker-build/versions.tf
- wrappers/docker-build/main.tf
- wrappers/docker-build/versions.tf
* Allow passing `builder` and `build_target` for `docker-build` module
Buildx and multi-stage images are great. Let's use them!
I believe these are backwards compatible
> feat: Add buildx and multi-stage build support to docker-build module
