- package.py
- package.tf
8a950ca *package.py - docker_image required for custom images for referencing*
d7d2fd8 *package.py - Uniform path output for zip skipping log records*
22d57b7 *package.py - Added support for docker images building*
9acb669 *package.py - Added docker_with_ssh_agent var usage*
> feat: docker image building for installing pip requirements independently from OS

- .pre-commit-config.yaml
- README.md
- examples/complete/main.tf
- iam.tf
- variables.tf
- versions.tf
> feat: Added support for policy_jsons (list of strings)

- README.md
- examples/alias/README.md
- examples/alias/versions.tf
- examples/async/README.md
- examples/async/versions.tf
- examples/build-package/README.md
- examples/build-package/versions.tf
- examples/complete/README.md
- examples/complete/versions.tf
- examples/deploy/README.md
- examples/deploy/versions.tf
- examples/simple/README.md
- examples/simple/versions.tf
- examples/with-efs/README.md
- examples/with-efs/versions.tf
- examples/with-vpc/README.md
- examples/with-vpc/versions.tf
- modules/alias/README.md
- modules/alias/versions.tf
- modules/deploy/README.md
- modules/deploy/versions.tf
- versions.tf
> feat: Updated range of supported versions of Terraform and providers

- modules/deploy/main.tf
> fix: Fixed CodeDeploy hooks

- README.md
- examples/alias/main.tf
- examples/complete/main.tf
- examples/deploy/main.tf
- main.tf
- modules/alias/README.md
- modules/alias/main.tf
> fix: Fixed apigateway trigger to use source_arn

- README.md
- variables.tf
Update memory size limit.
Max memory size limit is increased from 3008MB to 10GB.
> Fix memory size limit

- iam.tf
add iam CreateLogGroup permission
To be in line with the `AWSLambdaBasicExecutionRole`.
> fix(iam): add permission to create log group

- README.md
- iam.tf
This change allows for EventBridge to be used as a destination on success/failure
> feat: add eventbridge async permissions

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- outputs.tf
- add ci-cd workflow for pre-commit checks
- provide static checks for pull requests
- no
- copy of what is implemented in SQS module repository
> chore: add ci-cd workflow for pre-commit checks

- modules/deploy/main.tf
> fix: Fixed deprecated call to map() in deploy submodule

- README.md
> docs: Added a note for TFC/TFE customers

- README.md
- iam.tf
- main.tf
> feat: Added support for partition in IAM policies to work in GovCloud

- main.tf
> fix: Fixed max timeout for Lambda@Edge

- README.md
- examples/alias/README.md
- examples/alias/versions.tf
- examples/async/README.md
- examples/async/versions.tf
- examples/build-package/README.md
- examples/build-package/versions.tf
- examples/complete/README.md
- examples/complete/versions.tf
- examples/container-image/README.md
- examples/container-image/versions.tf
- examples/deploy/README.md
- examples/deploy/versions.tf
- examples/multiple-regions/README.md
- examples/multiple-regions/versions.tf
- examples/simple/README.md
- examples/simple/versions.tf
- examples/triggers/README.md
- examples/triggers/versions.tf
- examples/with-efs/README.md
- examples/with-efs/versions.tf
- examples/with-vpc/README.md
- examples/with-vpc/versions.tf
- iam.tf
- main.tf
- modules/alias/main.tf
- modules/alias/versions.tf
- modules/deploy/README.md
- modules/deploy/versions.tf
- versions.tf
This is the correction after https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/291
BREAKING CHANGES:
> feat: Updated AWS provider to version 4.8

- .pre-commit-config.yaml
- examples/container-image/README.md
- examples/container-image/main.tf
- examples/container-image/versions.tf
- modules/docker-build/README.md
- modules/docker-build/main.tf
> fix: Removed docker provider block from docker-build submodule

- iam.tf
> fix: Fixed policy name when create_role is false

- examples/event-source-mapping/main.tf
- main.tf
Enhance configuration of event source mappings to support multiple filters.
Fixes #350 
none
> feat: Allow multiple filters in event source mappings

- README.md
Document how and when poetry dependency manager is activated.
Fixes #436 
Fixes #311 
No.
> docs: Document poetry install

- .pre-commit-config.yaml
- README.md
- examples/complete/main.tf
- main.tf
- variables.tf
> feat: Added timeouts for Lambda Functions

- examples/container-image/README.md
- examples/container-image/main.tf
- examples/container-image/outputs.tf
- modules/docker-build/README.md
Fixes https://github.com/terraform-aws-modules/terraform-aws-ecr/issues/34
> chore: Added example for container-image with ECR module

- examples/event-source-mapping/main.tf
- main.tf
Add `tumbling_window_in_seconds`. 
Bump rabbitmq version in examples to a supported version. 
Closes: https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/619
No.
> feat: Add `tumbling_window_in_seconds`

- main.tf
Support `aws_lambda_event_source_mapping.document_db_event_source_config`
https://github.com/hashicorp/terraform-provider-aws/pull/28586
No.
> feat: Support `aws_lambda_event_source_mapping.document_db_event_source_config`
